# marks=[81,96,79,86,92]
# print(marks[4])
# print(type(marks))
# marks[1]=10
# print(marks)
# print(marks[1:4]) 
# list=[22,33,44,55,66]
# list.append(77)
# print(list)
# # list.sort(reverse=True)
# # print(list)
# list.reverse()
# print(list)
# list.insert(0,11)
# print(list)
# list.remove(33)
# print(list)
# list.pop(2)
# list.pop()
# tup=(1,2,3,4)
# print(type(tup))
# print(tup[0])
# tup=("hello",)
# print(type(tup))
# tup1=(1,2,3,4)
# print(tup1[1:3])
# movie1=input("enter your favourite movie: ")
# movie2=input("enter your second favourite movie: ")
# movie3=input("enter your third favourite movie: ")
# favmovie=(movie1,movie2,movie3)
# print("your favourite movies are:",favmovie)
# list.z 
list=[]
list.append(input("enter a number: "))
listcopy=list.copy()
listcopy.reverse()
if listcopy==list :
    print("palindrome")
else:    print("not a palindrome")